const readCsv = require('../../lib/read-csv')
const fs = require('fs-extra')
const { join, dirname } = require('path')

const workspace = process.argv[2]
const version = process.argv[3]

const text = fs.readFileSync(join(__dirname, '../../cn-opcodes.csv'), 'utf-8')
const table = readCsv(text, null, { header: 0, skip: 1 })

const output = {}
for (let { Name: name, Scope: scope, TeamCraft: altname, [version]: opcode } of table) {
  if (!name || !opcode) {
    console.log(`Invalid row: ${name}, ${opcode}`)
    continue
  }

  if (!output[scope]) {
    output[scope] = []
  }

  output[scope].push({
    name: altname || name,
    opcode
  })
}

const scopes = ['ServerZoneIpc', 'ClientZoneIpc', 'ServerChatIpc', 'ClientChatIpc']
const tab = `    `

const outputFile = join(workspace, 'MachinaWrapper/Models/Sapphire/Ipcs_cn.cs')
const outputPath = dirname(outputFile)

fs.mkdirpSync(outputPath)

fs.writeFileSync(outputFile, `// Generated by https://github.com/zhyupe/ffxiv-opcode-worker

namespace Sapphire.Common.Packets
{
${scopes.map(key => `${tab}enum ${key}TypeCN : ushort
${tab}{
${(output[key] || []).sort((a, b) => a.name.localeCompare(b.name))
    .map(({ name, opcode }) => `${tab}${tab}${name} = ${opcode},`).join('\n')
}
${tab}};`).join('\n\n')}
}
`)
