const readCsv = require('../../lib/read-csv')
const fs = require('fs-extra')
const { join, dirname } = require('path')

const workspace = process.argv[2]
const version = process.argv[3]

const text = fs.readFileSync(join(__dirname, '../../cn-opcodes.csv'), 'utf-8')
const table = readCsv(text, null, { header: 0, skip: 1 })

const output = {}
console.log(table)
for (let { Name: name, Scope: scope, TeamCraft: altname, [version]: opcode } of table) {
  if (!name || !opcode) {
    console.log(`Invalid row: ${name}, ${opcode}`)
    continue
  }

  if (!output[scope]) {
    output[scope] = []
  }

  output[scope].push({
    name: altname || name,
    opcode
  })
}

const outputFile = join(workspace, 'MachinaWrapper/src/Models/Sapphire/Ipcs_cn.cs')
const outputPath = dirname(outputFile)

fs.mkdirpSync(outputPath)

fs.writeFileSync(outputFile,
  `// Generated by https://github.com/zhyupe/ffxiv-opcode-worker
namespace Sapphire.Common.Packets
{
${Object.keys(output).sort().map(key => `  enum ${key}TypeCN : ushort
  {
${output[key].sort((a, b) => a.name.localeCompare(b.name))
    .map(({ name, opcode }) => `    ${name} = ${opcode},`).join('\n')
}
  };`).join('\n\n')}
}
`)
